"""update_database_model

Revision ID: 0b471b249a7a
Revises: 8be5862291f2
Create Date: 2022-11-27 19:01:06.058782

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0b471b249a7a"
down_revision = "8be5862291f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "database_assignment_template",
        "assignment_template_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_index(
        "ix_database_assignment_template_assignment_template_id",
        table_name="database_assignment_template",
    )
    op.create_index(
        op.f("ix_database_assignment_template_assignment_template_id"),
        "database_assignment_template",
        ["assignment_template_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_database_assignment_template_assignment_template_id"),
        table_name="database_assignment_template",
    )
    op.create_index(
        "ix_database_assignment_template_assignment_template_id",
        "database_assignment_template",
        ["assignment_template_id"],
        unique=False,
    )
    op.alter_column(
        "database_assignment_template",
        "assignment_template_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###
