"""unique columns

Revision ID: 12930bdb40cf
Revises: fa19e641570c
Create Date: 2022-11-16 20:28:52.122888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12930bdb40cf'
down_revision = 'fa19e641570c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_column', sa.Column('is_unique', sa.Boolean(), nullable=True))
    op.alter_column('table_relation', 'relation_table_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('table_relation', 'table_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('table_relation', 'table_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('table_relation', 'relation_table_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('table_column', 'is_unique')
    # ### end Alembic commands ###
