"""autoincrement_column

Revision ID: 2a4f37fda6c7
Revises: 0b471b249a7a
Create Date: 2022-12-05 20:14:40.386142

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2a4f37fda6c7"
down_revision = "0b471b249a7a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "table_column_assignment_template",
        sa.Column("autoincrement_index", sa.Integer(), nullable=True),
    )
    op.add_column(
        "table_column_assignment_template",
        sa.Column("is_autoincrement", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("table_column_assignment_template", "is_autoincrement")
    op.drop_column("table_column_assignment_template", "autoincrement_index")
    # ### end Alembic commands ###
