"""course_template_extend

Revision ID: 36eec4f6174e
Revises: cd841218f10c
Create Date: 2022-11-11 22:08:10.709264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36eec4f6174e'
down_revision = 'cd841218f10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_course_template_id_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'course_template', ['course_template_id'], ['id'], ondelete='SET NULL')
    op.add_column('course_template', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('course_template', sa.Column('is_published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_template', 'is_published')
    op.drop_column('course_template', 'is_public')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key('course_course_template_id_fkey', 'course', 'course_template', ['course_template_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
