"""template_database

Revision ID: 8be5862291f2
Revises: 12930bdb40cf
Create Date: 2022-11-19 23:38:36.531999

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8be5862291f2"
down_revision = "12930bdb40cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "database_assignment_template",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "modified",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column("name", sa.String(length=500), nullable=True),
        sa.Column("assignment_template_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignment_template_id"], ["assignment_template.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_database_assignment_template_assignment_template_id"),
        "database_assignment_template",
        ["assignment_template_id"],
        unique=False,
    )
    op.create_table(
        "table_assignment_template",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "modified",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column("name", sa.String(length=500), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("database_assignment_template_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["database_assignment_template_id"],
            ["database_assignment_template.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_table_assignment_template_database_assignment_template_id"),
        "table_assignment_template",
        ["database_assignment_template_id"],
        unique=False,
    )
    op.create_table(
        "table_column_assignment_template",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "modified",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column("name", sa.String(length=500), nullable=True),
        sa.Column(
            "type",
            sa.Enum("INTEGER", "NUMERIC", "REAL", "TEXT", "BLOB", name="columntype"),
            nullable=False,
        ),
        sa.Column("length", sa.Integer(), nullable=True),
        sa.Column("is_null", sa.Boolean(), nullable=True),
        sa.Column("is_unique", sa.Boolean(), nullable=True),
        sa.Column("table_assignment_template_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["table_assignment_template_id"],
            ["table_assignment_template.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_table_column_assignment_template_table_assignment_template_id"),
        "table_column_assignment_template",
        ["table_assignment_template_id"],
        unique=False,
    )
    op.create_table(
        "table_relation_assignment_template",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "modified",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column("name", sa.String(length=500), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "NO_ACTION", "SET_NULL", "SET_DEFAULT", "CASCADE", name="relationaction"
            ),
            nullable=False,
        ),
        sa.Column("relation_column_name", sa.String(length=500), nullable=True),
        sa.Column("relation_table_id", sa.Integer(), nullable=False),
        sa.Column("table_column_name", sa.String(length=500), nullable=True),
        sa.Column("table_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["relation_table_id"], ["table_assignment_template.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["table_id"], ["table_assignment_template.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_table_relation_assignment_template_relation_table_id"),
        "table_relation_assignment_template",
        ["relation_table_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_table_relation_assignment_template_table_id"),
        "table_relation_assignment_template",
        ["table_id"],
        unique=False,
    )
    op.create_table(
        "table_column_data_template",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "modified",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column("value", sa.String(length=500), nullable=True),
        sa.Column("table_column_assignment_template_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["table_column_assignment_template_id"],
            ["table_column_assignment_template.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_table_column_data_template_table_column_assignment_template_id"),
        "table_column_data_template",
        ["table_column_assignment_template_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_table_column_data_template_table_column_assignment_template_id"),
        table_name="table_column_data_template",
    )
    op.drop_table("table_column_data_template")
    op.drop_index(
        op.f("ix_table_relation_assignment_template_table_id"),
        table_name="table_relation_assignment_template",
    )
    op.drop_index(
        op.f("ix_table_relation_assignment_template_relation_table_id"),
        table_name="table_relation_assignment_template",
    )
    op.drop_table("table_relation_assignment_template")
    op.drop_index(
        op.f("ix_table_column_assignment_template_table_assignment_template_id"),
        table_name="table_column_assignment_template",
    )
    op.drop_table("table_column_assignment_template")
    op.drop_index(
        op.f("ix_table_assignment_template_database_assignment_template_id"),
        table_name="table_assignment_template",
    )
    op.drop_table("table_assignment_template")
    op.drop_index(
        op.f("ix_database_assignment_template_assignment_template_id"),
        table_name="database_assignment_template",
    )
    op.drop_table("database_assignment_template")
    # ### end Alembic commands ###
