"""table_rows

Revision ID: c1bada470739
Revises: fce42ef1ebe1
Create Date: 2022-12-23 21:37:14.727329

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c1bada470739"
down_revision = "fce42ef1ebe1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "table_row_assignment_template",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "modified",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column("ordinal", sa.Integer(), nullable=True),
        sa.Column("table_assignment_template_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["table_assignment_template_id"],
            ["table_assignment_template.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_table_row_assignment_template_table_assignment_template_id"),
        "table_row_assignment_template",
        ["table_assignment_template_id"],
        unique=False,
    )
    op.add_column(
        "table_assignment_template",
        sa.Column("autoincrement_index", sa.Integer(), nullable=True),
    )
    op.drop_column("table_column_assignment_template", "autoincrement_index")
    op.add_column(
        "table_column_data_template",
        sa.Column("table_row_assignment_template_id", sa.Integer(), nullable=True),
    )
    op.create_index(
        op.f("ix_table_column_data_template_table_row_assignment_template_id"),
        "table_column_data_template",
        ["table_row_assignment_template_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "table_column_data_template",
        "table_row_assignment_template",
        ["table_row_assignment_template_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "table_column_data_template", type_="foreignkey")
    op.drop_index(
        op.f("ix_table_column_data_template_table_row_assignment_template_id"),
        table_name="table_column_data_template",
    )
    op.drop_column("table_column_data_template", "table_row_assignment_template_id")
    op.add_column(
        "table_column_assignment_template",
        sa.Column(
            "autoincrement_index", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("table_assignment_template", "autoincrement_index")
    op.drop_index(
        op.f("ix_table_row_assignment_template_table_assignment_template_id"),
        table_name="table_row_assignment_template",
    )
    op.drop_table("table_row_assignment_template")
    # ### end Alembic commands ###
