"""query_history

Revision ID: cd841218f10c
Revises: 04183585f1fc
Create Date: 2022-11-03 21:21:18.542035

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cd841218f10c"
down_revision = "04183585f1fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "query_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "modified",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column("query", sa.String(), nullable=True),
        sa.Column("is_valid", sa.Boolean(), nullable=True),
        sa.Column("assignment_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignment_id"], ["assignment.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_query_history_assignment_id"),
        "query_history",
        ["assignment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_query_history_assignment_id"), table_name="query_history")
    op.drop_table("query_history")
    # ### end Alembic commands ###
