"""assigment

Revision ID: e9f89acc3a9c
Revises: f997442dbaca
Create Date: 2022-11-03 21:18:59.265414

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e9f89acc3a9c"
down_revision = "f997442dbaca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assignment_template",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "modified",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column("ordinal", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("description", sa.String(length=5000), nullable=True),
        sa.Column("owner_solution", sa.String(), nullable=True),
        sa.Column("quiz_template_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quiz_template_id"], ["quiz_template.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assignment_template_quiz_template_id"),
        "assignment_template",
        ["quiz_template_id"],
        unique=False,
    )
    op.create_table(
        "assignment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "modified",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column("ordinal", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("description", sa.String(length=5000), nullable=True),
        sa.Column("solution", sa.String(), nullable=True),
        sa.Column("assignment_template_id", sa.Integer(), nullable=False),
        sa.Column("quiz_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignment_template_id"], ["assignment_template.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["quiz_id"], ["quiz.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assignment_assignment_template_id"),
        "assignment",
        ["assignment_template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assignment_quiz_id"), "assignment", ["quiz_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assignment_quiz_id"), table_name="assignment")
    op.drop_index(op.f("ix_assignment_assignment_template_id"), table_name="assignment")
    op.drop_table("assignment")
    op.drop_index(
        op.f("ix_assignment_template_quiz_template_id"),
        table_name="assignment_template",
    )
    op.drop_table("assignment_template")
    # ### end Alembic commands ###
