"""quiz

Revision ID: f997442dbaca
Revises: 96602f162633
Create Date: 2022-11-03 21:16:48.848269

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f997442dbaca"
down_revision = "96602f162633"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quiz_template",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "modified",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("course_template_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_template_id"], ["course_template.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quiz_template_course_template_id"),
        "quiz_template",
        ["course_template_id"],
        unique=False,
    )
    op.create_table(
        "quiz",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "modified",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column(
            "created",
            sa.DateTime(),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=True,
        ),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("quiz_template_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["course_id"], ["course.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["quiz_template_id"], ["quiz_template.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quiz_course_id"), "quiz", ["course_id"], unique=False)
    op.create_index(
        op.f("ix_quiz_quiz_template_id"), "quiz", ["quiz_template_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quiz_quiz_template_id"), table_name="quiz")
    op.drop_index(op.f("ix_quiz_course_id"), table_name="quiz")
    op.drop_table("quiz")
    op.drop_index(
        op.f("ix_quiz_template_course_template_id"), table_name="quiz_template"
    )
    op.drop_table("quiz_template")
    # ### end Alembic commands ###
