"""default value to column

Revision ID: fce42ef1ebe1
Revises: 2a4f37fda6c7
Create Date: 2022-12-18 19:32:17.775572

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fce42ef1ebe1"
down_revision = "2a4f37fda6c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "table_column_assignment_template",
        sa.Column("default_value", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("table_column_assignment_template", "default_value")
    # ### end Alembic commands ###
